#!/bin/bash

# journey
#
# Journey is a straightforward CLI journalling program that allows you to create, manage,
# and access daily entries with a text-file--based system, simplifying your
# journalling experience.
#
# Written by Noah Dominic Miranda Silvio
# Copyright (c) 2022 - 2023 Noah Dominic Miranda Silvio.
# All rights reserved.
#
# This software is released under the EU Public Licence v. 1.2.
#

print_manual() {
    echo "JOURNEY"
    echo
    echo "NAME"
    echo "       journey - A straightforward CLI journalling program"
    echo
    echo "SYNOPSIS"
    echo "       journey <command>"
    echo
    echo "COMMANDS"
    echo "       The following commands are supported by the Journey script:"
    echo
    echo "       init   Initialises the Journey base folder."
    echo
    echo "       new    Initialises a new journal entry for the current day and opens it"
    echo "              in the default editor."
    echo
    echo "       show   Displays the contents of the current day's journal entry using"
    echo "              the \`less\` pager."
    echo
    echo "       write  Opens the current day's journal entry in the default editor"
    echo "              for writing or editing."
    echo
    echo "       vim    Opens the current day's journal entry in Vim for writing or"
    echo "              editing."
    echo
    echo "       nano   Opens the current day's journal entry in the Nano editor for"
    echo "              writing or editing."
    echo
    echo "CONFIGURATION"
    echo "       Users can customise their default editor by editing the \`$EDITOR\`" 
    echo "       variable in the script."
    echo
    echo "AUTHOR"
    echo "       Written by Noah Dominic Miranda Silvio"
    echo
    echo "COPYRIGHT"
    echo "       This is software is released under the EU Public Licence v. 2.0"
    echo
    echo "BUGS"
    echo "       Please report any bugs or issues to \`noah@noahdominic.com\`."
}

EDITOR="vim"

JOURNEY_BASEPATH="$HOME/journey"
TODAY=$(date +'%Y/%m/%d')
TODAYS_ENTRY="$JOURNEY_BASEPATH/$TODAY"

write() {
    eval "$EDITOR" + "$TODAYS_ENTRY"
}

# Main command dispatcher
case "$1" in
    init)
        mkdir -p "$JOURNEY_BASEPATH"
        ;;
    new)
        inittoday
        write
        ;;
    show)
        less "$TODAYS_ENTRY"
        ;;
    write)
        write
        ;;
    vim)
        vim "$TODAYS_ENTRY"
        ;;
    nano)
        nano "$TODAYS_ENTRY"
        ;;
    *)
        print_manual | less
        ;;
esac
